# Generated by Django 3.1.4 on 2021-02-05 18:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SMS', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='leavereportstaffs',
            name='leave_status',
            field=models.IntegerField(default=0),
        ),
    ]
