# Generated by Django 3.1.4 on 2021-02-20 11:06

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('SMS', '0003_auto_20210214_1955'),
    ]

    operations = [
        migrations.AddField(
            model_name='staffs',
            name='profile_pic',
            field=models.FileField(default=django.utils.timezone.now, upload_to=''),
            preserve_default=False,
        ),
    ]
