# Generated by Django 3.1.4 on 2021-02-21 07:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('SMS', '0004_staffs_profile_pic'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='staffs',
            name='profile_pic',
        ),
    ]
